version: '3.5'
services:
    postgres:
        image: postgres:12
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
            PGDATA: /data/postgres
        ports:
            - "5432:5432"
    web:
        depends_on:
            - "postgres"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
 